---
- name: setup frontend server
  hosts: frontend
  become: true

  tasks:
  - name: disable the default nginx version
    ansible.builtin.command: dnf module disable nginx -y
  - name: enable nginx 1.24 version
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and Enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
  
  - name: remove default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: download frontend content
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip"
      dest: /tmp/frontend.zip

  - name: unzip frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: true

  - name: delete nginx default configuration file
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy nginx configuration file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted

      