---
- name: setup shipping server
  hosts: shipping 
  become: yes

  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: create shipping user
      ansible.builtin.user:
        name: roboshop
        state: present
        shell: /sbin/nologin
        