---
- name: setup user server
  hosts: user
  become: yes

  tasks:
    - name: disable nodejs default version
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enable nodejs version 
      ansible.builtin.command: dnf module enable nodejs:20 -y
      
    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: add application user
      ansible.builtin.user:
        name: roboshop
        state: present
        shell: /sbin/nologin
        home: /app

    - name: remove  application directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create application directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: download source code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
        dest: /tmp/user.zip
    - name: unzip user application code
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    - name: install npm dependencies
      community.general.npm:
        path: /app 

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: daemon reload and start user service
      ansible.builtin.systemd:
        name: user
        daemon_reload: yes
        state: started
        enabled: yes

    
